title = "my homepage | this is test"
css = ["/style.css"]
copyright = "/copy.html"
valid_extensions = [".md", ".py", ".ico", ".png", ".jpeg", ".jpg"]
icon = "/favicon.ico"
phone_icon = "/apple-touch-icon.png"
hidden_files = ["/copy.html", "/favicon.ico", "/apple-touch-icon.png"]
